name: Chop Shop
favicon: null
layout_spectrum: 0.44877
typography_spectrum: 0.63646
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff2f00'
    - '#999999'
    - '#145866'
    - '#ab5d4b'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
