name: Chop Shop
favicon: null
layout_spectrum: 0.4312671320512891
typography_spectrum: 0.852405866375193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9219005212653428
  lightness: 0.9158643228001893
  saturation: 0.2641807799227536
  rhythmicContrast: 0.3347029082942754
purpose: []
