name: Chop Shop Studio
favicon: null
layout_spectrum: 0.50999
typography_spectrum: 0.63166
title: The Designs of Thomas Romer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#71675e'
    - '#a6aaad'
    - '#1b1b1b'
    - '#dcdcdc'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
